# Generated by Django 4.2.16 on 2024-11-20 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('minutos', models.PositiveIntegerField()),
                ('segundos', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporizadores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
