# Generated by Django 4.2.16 on 2024-11-27 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chef', '0002_temporizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('categoria', models.CharField(choices=[('congelados', 'Congelados'), ('carnes', 'Carnes'), ('pescados', 'Pescados'), ('conservas', 'Conservas'), ('embalaje', 'Embalaje'), ('material_cocina', 'Material de Cocina')], max_length=100)),
                ('reparto', models.CharField(default='Lunes a Viernes', max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
