# Generated by Django 4.2.16 on 2024-11-30 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Galeria',
        ),
    ]
